openapi: 3.0.2
info:
  title: Category RESTful API
  description: API Spec for Category RESTful API
  version: 1.0.0
servers:
- url: https://localhost:3000/api
paths:
  "/categories":
    get:
      security:
      - categoryAuth: []
      tags:
      - Category API
      description: List all Categories
      summary: List all Categories
      responses:
        '200':
          description: Success get all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      "$ref": "#components/schemas/category"
    post:
      security:
      - categoryAuth: []
      tags:
      - Category API
      description: Add New Category
      summary: Add New Category
      requestBody:
        content:
          appliaction/json:
            schema:
              "$ref": "#components/schemas/createOrUpdateCategory"
      responses:
        '200':
          description: Success create Categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    "$ref": "#components/schemas/category"
  "/categories/{categoryId}":
    get:
      security:
      - categoryAuth: []
      tags:
      - Category API
      description: Get category by id
      summary: Get category by id
      parameters:
      - name: categoryID
        in: path
        description: Category Id
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Success create Categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    "$ref": "#components/schemas/category"
    put:
      security:
      - categoryAuth: []
      tags:
      - Category API
      description: Get category by id
      summary: Get category by id
      requestBody:
        content:
          appliaction/json:
            schema:
              "$ref": "#components/schemas/createOrUpdateCategory"
      parameters:
      - name: categoryID
        in: path
        description: Category Id
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Success create Categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    "$ref": "#components/schemas/category"
    delete:
      security:
      - categoryAuth: []
      tags:
      - Category API
      description: Delete category by id
      summary: Delete category by id
      parameters:
      - name: categoryID
        in: path
        description: Category Id
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Success delete Categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
components:
  securitySchemes:
    categoryAuth:
      type: apiKey
      in: header
      name: X-API-key
      description: Authentication for category API
  schemas:
    createOrUpdateCategory:
      type: object
      properties:
        name:
          type: string
    category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
